#убирать с предмета зачарования которые предмет не может иметь. 
#Например с земли будут убираться все зачарования, т.к у неё не может быть зачарований.
remove-invalid-enchants: false
#список нбт тегов для проверки.
nbt:
  #ЧУВСТВИТЕЛЬНЫЙ К РЕГИСТРУ.
  - Items
  - ActiveEffects
  - Command
  - CustomName
  - AttributeModifiers
  - Unbreakable
  - CustomPotionEffects
spawneggs:
  - Fuse
  - CustomName
  - powered
  - ActiveEffects
  - ExplosionPower
  - Size
armorstand:
  - EntityTag
writtenbook:
  - ClickEvent
  - run_command
inventory:
#Chest, Dropper, TrappedChest, Dispenser, HOPPER
  - BlockEntityTag
#Таймер.
Timer:
  #Время в секундах. Проверять инвентрать игроков каждые DALAY секундах
  #Лучше не маленькое время, т.к это не нужно.
  delay: 120
  #Проверять ли инвентарь игроков(Броня не входит сюда)
  #Не рекомендуется включать, т.к это не нужно.
  CheckInventory: false
  #Проверять ли броню?
  #Это можно оставить включёным. Т.к игроки както умудряются одеть читерскую броню.
  CheckArmor: true
  #Включить ли таймер?
  Enabled: true
#ignoreTag: unknown(рандомные цифры). #нужен для команд