#Фикс краша сервера с помощью голов без скина.
fix-skull-exploit: true
#убирать с предмета зачарования которые предмет не может иметь. 
#Например с земли будут убираться все зачарования, т.к у неё не может быть зачарований.
remove-invalid-enchants: false
#список нбт тегов для проверки.
nbt:
  #ЧУВСТВИТЕЛЬНЫЙ К РЕГИСТРУ.
  - Items
  - ActiveEffects
  - Command
  - CustomName
  - AttributeModifiers
  - Unbreakable
  - CustomPotionEffects
spawneggs:
  - Fuse
  - CustomName
  - powered
  - ActiveEffects
  - ExplosionPower
armorstand:
  - EntityTag
writtenbook:
  - ClickEvent
  - run_command
inventory:
#Chest, Dropper, TrappedChest, Dispenser
  - BlockEntityTag